<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="cwvsft25" name="com.ep.mmbr.api.test.TestRunner" tests="1" failures="1" timestamp="6 Nov 2014 10:32:20 GMT" time="12.066" errors="0">
  <testcase name="test" time="12.066" classname="com.ep.mmbr.api.test.TestRunner">
    <failure type="com.mongodb.MongoTimeoutException" message="Timed out after 10000 ms while waiting to connect. Client view of cluster state is {type=Unknown, servers=[{address=ec2-54-69-38-210.us-west-2.compute.amazonaws.com:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.ConnectException: Connection refused: connect}}]">
      <![CDATA[com.mongodb.MongoTimeoutException: Timed out after 10000 ms while waiting to connect. Client view of cluster state is {type=Unknown, servers=[{address=ec2-54-69-38-210.us-west-2.compute.amazonaws.com:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at com.mongodb.BaseCluster.getDescription(BaseCluster.java:128)
	at com.mongodb.DBTCPConnector.getClusterDescription(DBTCPConnector.java:396)
	at com.mongodb.DBTCPConnector.getType(DBTCPConnector.java:569)
	at com.mongodb.DBTCPConnector.getReplicaSetStatus(DBTCPConnector.java:364)
	at com.mongodb.Mongo.getReplicaSetStatus(Mongo.java:465)
	at com.mongodb.DB.getCommandReadPreference(DB.java:86)
	at com.mongodb.DB.command(DB.java:314)
	at com.mongodb.DB.command(DB.java:296)
	at com.mongodb.DBCollection.getCount(DBCollection.java:1188)
	at com.mongodb.DBCursor.count(DBCursor.java:668)
	at com.ep.mmbr.api.utilities.MangoDBConnection.getResult(MangoDBConnection.java:48)
	at com.ep.mmbr.api.test.TestRunner.test(TestRunner.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- com.ep.mmbr.api.test.TestRunner -->
